# Generated by Django 6.1.1 on 2026-09-24 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
